initial workflow

diff --git a/.github/workflows/ci-cd.yaml b/.github/workflows/ci-cd.yaml
--- a/.github/workflows/ci-cd.yaml
+++ b/.github/workflows/ci-cd.yaml
@@ -64,43 +64,43 @@ jobs:
       run: docker images  
 
     # 3. Spin up the containers (They will now successfully read the job-level Env vars)
-    - name: Prepare for e2e test
-      run: |
-        printenv | grep "DB"
-        docker compose up -d
-      env:
-        DB_HOST: ${{ vars.DB_HOST }} 
-        DB_USER: ${{ vars.DB_USER }}
-        DB_NAME: ${{ vars.DB_NAME }}
-        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
-        DB_ROOT_PASSWORD: ${{ secrets.DB_ROOT_PASSWORD }}
+    # - name: Prepare for e2e test
+    #   run: |
+    #     printenv | grep "DB"
+    #     docker compose up -d
+    #   env:
+    #     DB_HOST: ${{ vars.DB_HOST }} 
+    #     DB_USER: ${{ vars.DB_USER }}
+    #     DB_NAME: ${{ vars.DB_NAME }}
+    #     DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
+    #     DB_ROOT_PASSWORD: ${{ secrets.DB_ROOT_PASSWORD }}
    
-    # 4. Wait for the Flask app to be ready, then curl
-    - name: Test e2e
-      run: |
-        sleep 30
-        echo "=== Run 1: Checking for Success Message ==="
-        # Run curl and save response to a variable
-        RESPONSE_1=$(curl -s -f http://localhost:5000/)
+    # # 4. Wait for the Flask app to be ready, then curl
+    # - name: Test e2e
+    #   run: |
+    #     sleep 30
+    #     echo "=== Run 1: Checking for Success Message ==="
+    #     # Run curl and save response to a variable
+    #     RESPONSE_1=$(curl -s -f http://localhost:5000/)
         
-        # Verify the success message exists in the output
-        if echo "$RESPONSE_1" | grep -q "Data fetched successfully from the database."; then
-          echo "✓ Success message found!"
-        else
-          echo "✗ Expected success message not found!"
-          exit 1
-        fi
-        curl -fs http://localhost:5000/ > /dev/null
+    #     # Verify the success message exists in the output
+    #     if echo "$RESPONSE_1" | grep -q "Data fetched successfully from the database."; then
+    #       echo "✓ Success message found!"
+    #     else
+    #       echo "✗ Expected success message not found!"
+    #       exit 1
+    #     fi
+    #     curl -fs http://localhost:5000/ > /dev/null
         
-        curl -fs http://localhost:5000/ > /dev/null
+    #     curl -fs http://localhost:5000/ > /dev/null
         
-        ENTRY_COUNT=$(curl -fs http://localhost:5000/ | jq '.previous_entries | length')
-        if [ "$ENTRY_COUNT" -eq 4 ]; then
-          echo "✓ Success! The database accurately tracked 4 entries."
-        else
-          echo "✗ Error! Expected 4 entries, but found $ENTRY_COUNT."
-          exit 1
-        fi 
+    #     ENTRY_COUNT=$(curl -fs http://localhost:5000/ | jq '.previous_entries | length')
+    #     if [ "$ENTRY_COUNT" -eq 4 ]; then
+    #       echo "✓ Success! The database accurately tracked 4 entries."
+    #     else
+    #       echo "✗ Error! Expected 4 entries, but found $ENTRY_COUNT."
+    #       exit 1
+    #     fi 
     
     - name: Configure AWS Credentials via OIDC
       uses: aws-actions/configure-aws-credentials@v6
