initial workflow

diff --git a/.github/workflows/install-and-unit-test.yaml b/.github/workflows/install-and-unit-test.yaml
--- a/.github/workflows/install-and-unit-test.yaml
+++ b/.github/workflows/install-and-unit-test.yaml
@@ -24,26 +24,24 @@ jobs:
     - name: Initiate report artifact
       run: |
         cat << EOF > report.txt
-        =================================
-        install and unit test started
-        =================================
+        ========================================
+        [$(date)]install and unit test started
+        ========================================
         
 #==============================================================================================
 #                                             install
 #==============================================================================================
     - name: Install dependencies
       run: |
-        echo "installing dependencies..." >> report.txt
-        
+
         python -m pip install --upgrade pip
         pip install -r requirements.txt
         
         if [ $? -eq 0 ]; then
-          echo "Result: SUCCESS" >> report.txt
+          echo "[$(date)]dependencies installed sccessfully" >> report.txt
         else
-          echo Result: FAILED >> reoprt.txt
-        
-          exit 1 # Ensures the CI step actually fails if the install failed
+          echo "[$(date)]failed installing dependencies " >> report.txt
+          exit 1 
         fi
         
 #==============================================================================================
@@ -51,7 +49,7 @@ jobs:
 #==============================================================================================
     - name: Run App and Test with Curl
       run: |
-        echo "running the app in the background..." >> report.txt
+        echo "[$(date)]running the app in the background" >> report.txt
         python app.py &
         
 
@@ -60,9 +58,16 @@ jobs:
 #==============================================================================================
     - name: Unit test
       run: |
-        echo "running unit test..." >> report.txt
         sleep 3
         RESULT=$(curl -f http://127.0.0.1:5000/)
+        if echo "$RESULT" | grep -q "current_entry"; then
+          echo "[$(date)]uinit test sucess" >> report.txt
+        else
+          echo "[$(date)]unit test fail" >> report.txt
+          echo "$RESULT" >> report.txt
+          exit 1
+        fi
+
         echo "result: $RESULT" >> report.txt
         
     - name: Upload artifact
